import React from 'react';
import { X, Printer, Download } from 'lucide-react';

interface FacsimileModalProps {
  isOpen: boolean;
  onClose: () => void;
  record: any;
  recordType: string;
  onPrint?: () => void;
  onDownload?: () => void;
}

export default function FacsimileModal({
  isOpen,
  onClose,
  record,
  recordType,
  onPrint,
  onDownload
}: FacsimileModalProps) {
  if (!isOpen || !record) return null;

  const handlePrint = () => {
    window.print();
    onPrint?.();
  };

  const handleDownload = () => {
    // Create a printable version of the facsimile
    const printContent = document.getElementById('facsimile-content');
    if (printContent) {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>${recordType} Facsimile - ${record.id || 'Record'}</title>
              <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
                .company-name { font-size: 18px; font-weight: bold; }
                .sub-client { font-size: 14px; color: #666; margin-top: 5px; }
                .record-details { margin: 20px 0; }
                .field-group { margin: 15px 0; }
                .field-label { font-weight: bold; display: inline-block; width: 150px; }
                .field-value { display: inline-block; }
                .footer { margin-top: 30px; border-top: 1px solid #ccc; padding-top: 10px; font-size: 12px; color: #666; }
                @media print {
                  body { margin: 0; }
                  .no-print { display: none; }
                }
              </style>
            </head>
            <body>
              <div class="header">
                <div class="company-name">${record.sub_client_company || record.client_name || record.customer_name || 'Customer Company Name'}</div>
                <div class="sub-client">Sub-Client Company Name</div>
                <div style="font-size: 12px; color: #999; margin-top: 10px;">Generated on: ${new Date().toLocaleDateString()}</div>
              </div>
              <div class="record-details">
                <h3>${recordType} Details</h3>
                ${printContent.querySelector('.record-details')?.innerHTML || ''}
              </div>
              <div class="footer">
                <p>This is an official facsimile generated by ${record.primary_client_name || record.tenant_name || 'Primary Client Name'}.</p>
                <p>For questions or concerns, please contact your account representative.</p>
              </div>
            </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.print();
      }
    }
    onDownload?.();
  };

  const renderRecordDetails = () => {
    switch (recordType.toLowerCase()) {
      case 'timecard':
        // Create sample timecard data for the week - in real implementation, this would come from the database
        const sampleTimecardData = [
          { date: '9/7/2025', clockIn: '9:07am', clockOut: '5:20pm', clockIn2: '', clockOut2: '', regularHours: 8, otHours: 0.22, totalHours: 8.22 },
          { date: '9/8/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/9/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/10/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/11/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/12/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/13/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 }
        ];
        
        const totalRegular = sampleTimecardData.reduce((sum, day) => sum + day.regularHours, 0);
        const totalOT = sampleTimecardData.reduce((sum, day) => sum + day.otHours, 0);
        const grandTotal = totalRegular + totalOT;
        
        return (
          <div className="bg-white">
            {/* Professional Header Section */}
            <div className="bg-gradient-to-r from-blue-600 to-blue-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">TIMECARD REPORT</h3>
                    <p className="text-blue-100 text-sm">Employee Time & Attendance Summary</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-blue-100">Record ID</div>
                  <div className="font-mono text-lg">{record.id || 'TC-001'}</div>
                </div>
              </div>
            </div>

            {/* Employee Information Card */}
            <div className="bg-gray-50 border-l-4 border-blue-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Pay Period</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.period_start || '9/7/2025'} - {record.period_end || '9/13/2025'}</div>
                </div>
              </div>
            </div>

            {/* Time Summary Section */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Time Summary</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden">
                <table className="w-full text-sm">
                  <thead className="bg-gradient-to-r from-gray-50 to-gray-100">
                    <tr>
                      <th className="border-r border-gray-200 px-4 py-3 text-left font-semibold text-gray-700">Work Date</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Clock In</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Clock Out</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Clock In</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Clock Out</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Regular Hrs</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">OT Hrs</th>
                      <th className="px-4 py-3 text-center font-semibold text-gray-700">Total Hrs</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sampleTimecardData.map((day, index) => (
                      <tr key={index} className={`border-t border-gray-200 ${index % 2 === 0 ? 'bg-white' : 'bg-gray-50'}`}>
                        <td className="border-r border-gray-200 px-4 py-3 font-medium">{day.date}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center">{day.clockIn}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center">{day.clockOut}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center">{day.clockIn2 || '-'}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center">{day.clockOut2 || '-'}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center font-medium">{day.regularHours || '-'}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center font-medium">{day.otHours || '-'}</td>
                        <td className="px-4 py-3 text-center font-bold">{day.totalHours || '-'}</td>
                      </tr>
                    ))}
                    {/* Pay Period Totals Row */}
                    <tr className="border-t-2 border-blue-300 bg-gradient-to-r from-blue-50 to-blue-100">
                      <td className="border-r border-gray-200 px-4 py-4 font-bold text-blue-900">PAY PERIOD TOTALS</td>
                      <td className="border-r border-gray-200 px-4 py-4"></td>
                      <td className="border-r border-gray-200 px-4 py-4"></td>
                      <td className="border-r border-gray-200 px-4 py-4"></td>
                      <td className="border-r border-gray-200 px-4 py-4"></td>
                      <td className="border-r border-gray-200 px-4 py-4 text-center font-bold text-blue-900">{totalRegular}</td>
                      <td className="border-r border-gray-200 px-4 py-4 text-center font-bold text-blue-900">{totalOT.toFixed(2)}</td>
                      <td className="px-4 py-4 text-center font-bold text-lg text-blue-900">{grandTotal.toFixed(2)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* Additional Information */}
            {record.notes && (
              <div className="mx-6 mb-6">
                <div className="flex items-center space-x-2 mb-3">
                  <svg className="w-5 h-5 text-yellow-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                  </svg>
                  <h4 className="font-semibold text-gray-900">Notes & Comments</h4>
                </div>
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                  <div className="text-gray-900">{record.notes}</div>
                </div>
              </div>
            )}
          </div>
        );

      case 'invoice':
        return (
          <div className="bg-white">
            {/* Professional Header Section */}
            <div className="bg-gradient-to-r from-green-600 to-green-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M4 4a2 2 0 00-2 2v1h16V6a2 2 0 00-2-2H4zM18 9H2v5a2 2 0 002 2h12a2 2 0 002-2V9zM4 13a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm5-1a1 1 0 100 2h1a1 1 0 100-2H9z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">INVOICE</h3>
                    <p className="text-green-100 text-sm">Billing & Payment Document</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-green-100">Invoice #</div>
                  <div className="font-mono text-lg">{record.invoice_number || 'INV-001'}</div>
                </div>
              </div>
            </div>

            {/* Employee Information Card */}
            <div className="bg-gray-50 border-l-4 border-green-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
              </div>
            </div>

            {/* Invoice Details */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Invoice Details</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Client</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.client_name || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Invoice Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.invoice_date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Due Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.due_date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Amount</label>
                    <div className="text-2xl font-bold text-green-600 mt-1">${record.amount || '0.00'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Status</label>
                    <div className="mt-1">
                      <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                        record.status === 'paid' ? 'bg-green-100 text-green-800' :
                        record.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-red-100 text-red-800'
                      }`}>
                        {record.status || 'Unknown'}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Description */}
            {record.description && (
              <div className="mx-6 mb-6">
                <div className="flex items-center space-x-2 mb-3">
                  <svg className="w-5 h-5 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
                  </svg>
                  <h4 className="font-semibold text-gray-900">Description</h4>
                </div>
                <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
                  <div className="text-gray-900">{record.description}</div>
                </div>
              </div>
            )}
          </div>
        );

      case 'expense':
        return (
          <div className="bg-white">
            {/* Professional Header Section */}
            <div className="bg-gradient-to-r from-orange-600 to-orange-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">EXPENSE REPORT</h3>
                    <p className="text-orange-100 text-sm">Employee Expense Reimbursement</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-orange-100">Expense ID</div>
                  <div className="font-mono text-lg">{record.id || 'EXP-001'}</div>
                </div>
              </div>
            </div>

            {/* Employee Information Card */}
            <div className="bg-gray-50 border-l-4 border-orange-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-orange-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
              </div>
            </div>

            {/* Expense Details */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Expense Details</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Category</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.category || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Amount</label>
                    <div className="text-2xl font-bold text-orange-600 mt-1">${record.amount || '0.00'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Status</label>
                    <div className="mt-1">
                      <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                        record.status === 'approved' ? 'bg-green-100 text-green-800' :
                        record.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-red-100 text-red-800'
                      }`}>
                        {record.status || 'Unknown'}
                      </span>
                    </div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Submitted</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.submitted_date || 'N/A'}</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Notes */}
            {record.notes && (
              <div className="mx-6 mb-6">
                <div className="flex items-center space-x-2 mb-3">
                  <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
                  </svg>
                  <h4 className="font-semibold text-gray-900">Notes & Comments</h4>
                </div>
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                  <div className="text-gray-900">{record.notes}</div>
                </div>
              </div>
            )}
          </div>
        );

      case 'pay_statement':
        return (
          <div className="bg-white">
            {/* Professional Header Section */}
            <div className="bg-gradient-to-r from-indigo-600 to-indigo-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M4 4a2 2 0 00-2 2v1h16V6a2 2 0 00-2-2H4zM18 9H2v5a2 2 0 002 2h12a2 2 0 002-2V9zM4 13a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm5-1a1 1 0 100 2h1a1 1 0 100-2H9z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">PAY STATEMENT</h3>
                    <p className="text-indigo-100 text-sm">Employee Payroll Statement</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-indigo-100">Check #</div>
                  <div className="font-mono text-lg">{record.check_number || 'CHK-001'}</div>
                </div>
              </div>
            </div>

            {/* Employee Information Card */}
            <div className="bg-gray-50 border-l-4 border-indigo-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-indigo-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
              </div>
            </div>

            {/* Pay Period Information */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Pay Period Information</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Pay Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.pay_date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Period Start</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.pay_period_start || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Period End</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.pay_period_end || 'N/A'}</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Earnings & Deductions */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Earnings & Deductions</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-2 gap-8">
                  <div>
                    <h5 className="font-semibold text-green-700 mb-3">Earnings</h5>
                    <div className="space-y-2">
                      <div className="flex justify-between">
                        <span className="text-gray-600">Gross Pay:</span>
                        <span className="font-semibold text-green-600">${record.gross_pay || '0.00'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Regular Hours:</span>
                        <span className="font-medium">{record.regular_hours || '0'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Overtime Hours:</span>
                        <span className="font-medium">{record.overtime_hours || '0'}</span>
                      </div>
                    </div>
                  </div>
                  <div>
                    <h5 className="font-semibold text-red-700 mb-3">Deductions</h5>
                    <div className="space-y-2">
                      <div className="flex justify-between">
                        <span className="text-gray-600">Federal Tax:</span>
                        <span className="font-medium text-red-600">${record.federal_tax || '0.00'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">State Tax:</span>
                        <span className="font-medium text-red-600">${record.state_tax || '0.00'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Social Security:</span>
                        <span className="font-medium text-red-600">${record.social_security || '0.00'}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Medicare:</span>
                        <span className="font-medium text-red-600">${record.medicare || '0.00'}</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="border-t border-gray-200 mt-6 pt-4">
                  <div className="flex justify-between items-center">
                    <span className="text-lg font-semibold text-gray-900">Net Pay:</span>
                    <span className="text-2xl font-bold text-indigo-600">${record.net_pay || '0.00'}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Year-to-Date Summary */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-3">
                <svg className="w-5 h-5 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 4a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900">Year-to-Date Summary</h4>
              </div>
              <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
                <div className="grid grid-cols-4 gap-4 text-center">
                  <div>
                    <div className="text-sm text-gray-500 uppercase tracking-wide">YTD Gross</div>
                    <div className="text-lg font-semibold text-gray-900">${record.ytd_gross || '0.00'}</div>
                  </div>
                  <div>
                    <div className="text-sm text-gray-500 uppercase tracking-wide">YTD Federal</div>
                    <div className="text-lg font-semibold text-gray-900">${record.ytd_federal || '0.00'}</div>
                  </div>
                  <div>
                    <div className="text-sm text-gray-500 uppercase tracking-wide">YTD Social Security</div>
                    <div className="text-lg font-semibold text-gray-900">${record.ytd_social_security || '0.00'}</div>
                  </div>
                  <div>
                    <div className="text-sm text-gray-500 uppercase tracking-wide">YTD Medicare</div>
                    <div className="text-lg font-semibold text-gray-900">${record.ytd_medicare || '0.00'}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case 'job':
        return (
          <div className="bg-white">
            {/* Professional Header Section */}
            <div className="bg-gradient-to-r from-teal-600 to-teal-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.57A22.952 22.952 0 0110 13a22.95 22.95 0 01-8-1.43V8a2 2 0 012-2h2zm2-1a1 1 0 011-1h2a1 1 0 011 1v1H8V5zm1 5a1 1 0 011-1h.01a1 1 0 110 2H10a1 1 0 01-1-1z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">JOB CATALOG</h3>
                    <p className="text-teal-100 text-sm">Position & Role Information</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-teal-100">Job ID</div>
                  <div className="font-mono text-lg">{record.job_id || record.id || 'JOB-001'}</div>
                </div>
              </div>
            </div>

            {/* Employee Information Card */}
            <div className="bg-gray-50 border-l-4 border-teal-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-teal-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
              </div>
            </div>

            {/* Job Details */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Position Details</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-2 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Job Title</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.job_title || record.title || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Department</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.department || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Division</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.division || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Location</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.location || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Pay Type</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.pay_type || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">FLSA Status</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.flsa_status || 'N/A'}</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Compensation */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Compensation Information</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Salary/Rate</label>
                    <div className="text-2xl font-bold text-green-600 mt-1">${record.salary || record.hourly_rate || '0.00'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Status</label>
                    <div className="mt-1">
                      <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                        record.status === 'active' ? 'bg-green-100 text-green-800' :
                        record.status === 'inactive' ? 'bg-red-100 text-red-800' :
                        'bg-gray-100 text-gray-800'
                      }`}>
                        {record.status || 'Unknown'}
                      </span>
                    </div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Hire Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.hire_date || 'N/A'}</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Job Description */}
            {record.job_description && (
              <div className="mx-6 mb-6">
                <div className="flex items-center space-x-2 mb-3">
                  <svg className="w-5 h-5 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
                  </svg>
                  <h4 className="font-semibold text-gray-900">Job Description</h4>
                </div>
                <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
                  <div className="text-gray-900">{record.job_description}</div>
                </div>
              </div>
            )}
          </div>
        );

      case 'tax_w2':
        return (
          <div className="bg-white">
            {/* Professional Header Section */}
            <div className="bg-gradient-to-r from-purple-600 to-purple-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">TAX DOCUMENT ({record.form_type || 'W-2'})</h3>
                    <p className="text-purple-100 text-sm">{
                      record.form_type === 'W-2' ? 'Annual Wage & Tax Statement' :
                      record.form_type === '1099-NEC' ? 'Nonemployee Compensation' :
                      record.form_type === '1099-MISC' ? 'Miscellaneous Income' :
                      record.form_type === 'W-4' ? 'Employee Withholding Certificate' :
                      record.form_type === '1099-INT' ? 'Interest Income' :
                      record.form_type === '1099-DIV' ? 'Dividend Income' :
                      'Tax Document'
                    }</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-purple-100">Tax Year</div>
                  <div className="font-mono text-lg">{record.tax_year || '2025'}</div>
                </div>
              </div>
            </div>

            {/* Employee Information Card */}
            <div className="bg-gray-50 border-l-4 border-purple-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
              </div>
            </div>

            {/* Tax Information */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Tax Information</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                {/* W-2 Form Fields */}
                {(record.form_type === 'W-2' || !record.form_type) && (
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Wages, Tips & Compensation</label>
                      <div className="text-2xl font-bold text-green-600 mt-1">${record.wages_tips_compensation || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Federal Income Tax Withheld</label>
                      <div className="text-2xl font-bold text-red-600 mt-1">${record.federal_income_tax_withheld || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Social Security Wages</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${record.social_security_wages || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Social Security Tax Withheld</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${record.social_security_tax_withheld || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Medicare Wages</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${record.medicare_wages || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Medicare Tax Withheld</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${record.medicare_tax_withheld || '0.00'}</div>
                    </div>
                  </div>
                )}

                {/* 1099-NEC Form Fields */}
                {record.form_type === '1099-NEC' && (
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Nonemployee Compensation</label>
                      <div className="text-2xl font-bold text-green-600 mt-1">${record.nonemployee_compensation || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Federal Income Tax Withheld</label>
                      <div className="text-2xl font-bold text-red-600 mt-1">${record.federal_income_tax_withheld || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">State Tax Withheld</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${record.state_income_tax || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">State/Payer's State No.</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.state_code || 'N/A'}</div>
                    </div>
                  </div>
                )}

                {/* 1099-MISC Form Fields */}
                {record.form_type === '1099-MISC' && (
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Miscellaneous Income</label>
                      <div className="text-2xl font-bold text-green-600 mt-1">${record.misc_income || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Federal Income Tax Withheld</label>
                      <div className="text-2xl font-bold text-red-600 mt-1">${record.federal_income_tax_withheld || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">State Tax Withheld</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${record.state_income_tax || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">State/Payer's State No.</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.state_code || 'N/A'}</div>
                    </div>
                  </div>
                )}

                {/* W-4 Form Fields */}
                {record.form_type === 'W-4' && (
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Filing Status</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.filing_status || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Number of Dependents</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.dependents || '0'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Tax Jurisdiction</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.tax_jurisdiction || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">State Code</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.state_code || 'N/A'}</div>
                    </div>
                  </div>
                )}

                {/* Other Form Types - Generic Display */}
                {record.form_type && !['W-2', '1099-NEC', '1099-MISC', 'W-4'].includes(record.form_type) && (
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Form Type</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.form_type}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Tax Year</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.tax_year || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Federal Income Tax Withheld</label>
                      <div className="text-2xl font-bold text-red-600 mt-1">${record.federal_income_tax_withheld || '0.00'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">State Tax Withheld</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${record.state_income_tax || '0.00'}</div>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Document Status */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-3">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900">Document Status</h4>
              </div>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <span className="text-sm font-medium text-gray-500 uppercase tracking-wide">Status</span>
                    <div className="mt-1">
                      <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                        record.document_status === 'issued' ? 'bg-green-100 text-green-800' :
                        record.document_status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-gray-100 text-gray-800'
                      }`}>
                        {record.document_status || 'Unknown'}
                      </span>
                    </div>
                  </div>
                  <div>
                    <span className="text-sm font-medium text-gray-500 uppercase tracking-wide">Form Type</span>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.form_type || 'W-2'}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      default:
        return (
          <div className="bg-white">
            {/* Professional Header Section */}
            <div className="bg-gradient-to-r from-gray-600 to-gray-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">{recordType.toUpperCase()} RECORD</h3>
                    <p className="text-gray-100 text-sm">Employee Record Details</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-gray-100">Record ID</div>
                  <div className="font-mono text-lg">{record.id || 'REC-001'}</div>
                </div>
              </div>
            </div>

            {/* Employee Information Card */}
            <div className="bg-gray-50 border-l-4 border-gray-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-gray-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
              </div>
            </div>

            {/* Record Details */}
            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Record Details</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-2 gap-6">
                  {Object.entries(record)
                    .filter(([key]) => !['employee_name', 'employee_id', 'id'].includes(key))
                    .map(([key, value]) => (
                    <div key={key}>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">
                        {key.replace(/_/g, ' ')}
                      </label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{String(value) || 'N/A'}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        );
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-7xl w-full max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 no-print">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">
              {recordType} Facsimile
            </h2>
            <p className="text-sm text-gray-600 mt-1">
              Record ID: {record.id || record.invoice_number || record.expense_id || 'N/A'}
            </p>
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={handleDownload}
              className="inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              <Download className="h-4 w-4 mr-2" />
              Download
            </button>
            <button
              onClick={handlePrint}
              className="inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              <Printer className="h-4 w-4 mr-2" />
              Print
            </button>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 rounded-md p-2"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[calc(90vh-120px)]">
          <div id="facsimile-content">
            {/* Company Header */}
            <div className="header mb-6 pb-4 border-b-2 border-gray-900">
              <div className="company-name text-xl font-bold text-gray-900">
                {record.sub_client_company || record.client_name || record.customer_name || 'Customer Company Name'}
              </div>
              <div className="text-sm text-gray-500 mt-2">
                Generated on: {new Date().toLocaleDateString()}
              </div>
            </div>

            {/* Record Details */}
            <div className="record-details">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">
                {recordType} Details
              </h3>
              {renderRecordDetails()}
            </div>

            {/* Footer */}
            <div className="footer mt-8 pt-4 border-t border-gray-300 text-xs text-gray-500">
              <p>This is an official facsimile generated by {record.primary_client_name || record.tenant_name || 'Primary Client Name'}.</p>
              <p>For questions or concerns, please contact your account representative.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
