
import React from 'react';
import { X, Printer, Download } from 'lucide-react';

interface FacsimileModalProps {
  isOpen: boolean;
  onClose: () => void;
  record: any;
  recordType: string;
  onPrint?: () => void;
  onDownload?: () => void;
}

export default function FacsimileModal({
  isOpen,
  onClose,
  record,
  recordType,
  onPrint,
  onDownload
}: FacsimileModalProps) {
  if (!isOpen || !record) return null;

  const handlePrint = () => {
    window.print();
    onPrint?.();
  };

  const handleDownload = () => {
    const printContent = document.getElementById('facsimile-content');
    if (printContent) {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>${recordType} Facsimile - ${record.id || 'Record'}</title>
              <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
                .company-name { font-size: 18px; font-weight: bold; }
                .record-details { margin: 20px 0; }
                .field-group { margin: 15px 0; }
                .field-label { font-weight: bold; display: inline-block; width: 150px; }
                .field-value { display: inline-block; }
                .footer { margin-top: 30px; border-top: 1px solid #ccc; padding-top: 10px; font-size: 12px; color: #666; }
                @media print {
                  body { margin: 0; }
                  .no-print { display: none; }
                }
              </style>
            </head>
            <body>
              <div class="header">
                <div class="company-name">${record.sub_client_company || record.client_name || record.customer_name || 'Customer Company Name'}</div>
                <div style="font-size: 12px; color: #999; margin-top: 10px;">Generated on: ${new Date().toLocaleDateString()}</div>
              </div>
              <div class="record-details">
                ${printContent.querySelector('.record-details')?.innerHTML || ''}
              </div>
              <div class="footer">
                <p>This is an official facsimile generated by ${record.primary_client_name || record.tenant_name || 'Primary Client Name'}.</p>
                <p>For questions or concerns, please contact your account representative.</p>
              </div>
            </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.print();
      }
    }
    onDownload?.();
  };

  const renderRecordDetails = () => {
    switch (recordType.toLowerCase()) {
      case 'timecard':
        const sampleTimecardData = [
          { date: '9/7/2025', clockIn: '9:07am', clockOut: '5:20pm', clockIn2: '', clockOut2: '', regularHours: 8, otHours: 0.22, totalHours: 8.22 },
          { date: '9/8/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/9/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/10/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/11/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/12/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 },
          { date: '9/13/2025', clockIn: '', clockOut: '', clockIn2: '', clockOut2: '', regularHours: 0, otHours: 0, totalHours: 0 }
        ];
        
        const totalRegular = sampleTimecardData.reduce((sum, day) => sum + day.regularHours, 0);
        const totalOT = sampleTimecardData.reduce((sum, day) => sum + day.otHours, 0);
        const grandTotal = totalRegular + totalOT;
        
        return (
          <div className="bg-white">
            <div className="bg-gradient-to-r from-blue-600 to-blue-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">TIMECARD REPORT</h3>
                    <p className="text-blue-100 text-sm">Employee Time & Attendance Summary</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-blue-100">Record ID</div>
                  <div className="font-mono text-lg">{record.id || 'TC-001'}</div>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 border-l-4 border-blue-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Pay Period</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.period_start || '9/7/2025'} - {record.period_end || '9/13/2025'}</div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Time Summary</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden">
                <table className="w-full text-sm">
                  <thead className="bg-gradient-to-r from-gray-50 to-gray-100">
                    <tr>
                      <th className="border-r border-gray-200 px-4 py-3 text-left font-semibold text-gray-700">Work Date</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Clock In</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Clock Out</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Clock In</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Clock Out</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">Regular Hrs</th>
                      <th className="border-r border-gray-200 px-4 py-3 text-center font-semibold text-gray-700">OT Hrs</th>
                      <th className="px-4 py-3 text-center font-semibold text-gray-700">Total Hrs</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sampleTimecardData.map((day, index) => (
                      <tr key={index} className={`border-t border-gray-200 ${index % 2 === 0 ? 'bg-white' : 'bg-gray-50'}`}>
                        <td className="border-r border-gray-200 px-4 py-3 font-medium">{day.date}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center">{day.clockIn}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center">{day.clockOut}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center">{day.clockIn2 || '-'}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center">{day.clockOut2 || '-'}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center font-medium">{day.regularHours || '-'}</td>
                        <td className="border-r border-gray-200 px-4 py-3 text-center font-medium">{day.otHours || '-'}</td>
                        <td className="px-4 py-3 text-center font-bold">{day.totalHours || '-'}</td>
                      </tr>
                    ))}
                    <tr className="border-t-2 border-blue-300 bg-gradient-to-r from-blue-50 to-blue-100">
                      <td className="border-r border-gray-200 px-4 py-4 font-bold text-blue-900">PAY PERIOD TOTALS</td>
                      <td className="border-r border-gray-200 px-4 py-4"></td>
                      <td className="border-r border-gray-200 px-4 py-4"></td>
                      <td className="border-r border-gray-200 px-4 py-4"></td>
                      <td className="border-r border-gray-200 px-4 py-4"></td>
                      <td className="border-r border-gray-200 px-4 py-4 text-center font-bold text-blue-900">{totalRegular}</td>
                      <td className="border-r border-gray-200 px-4 py-4 text-center font-bold text-blue-900">{totalOT.toFixed(2)}</td>
                      <td className="px-4 py-4 text-center font-bold text-lg text-blue-900">{grandTotal.toFixed(2)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {record.notes && (
              <div className="mx-6 mb-6">
                <div className="flex items-center space-x-2 mb-3">
                  <svg className="w-5 h-5 text-yellow-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                  </svg>
                  <h4 className="font-semibold text-gray-900">Notes & Comments</h4>
                </div>
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                  <div className="text-gray-900">{record.notes}</div>
                </div>
              </div>
            )}
          </div>
        );

      case 'invoice':
        return (
          <div className="bg-white">
            <div className="bg-gradient-to-r from-green-600 to-green-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M4 4a2 2 0 00-2 2v1h16V6a2 2 0 00-2-2H4zM18 9H2v5a2 2 0 002 2h12a2 2 0 002-2V9zM4 13a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm5-1a1 1 0 100 2h1a1 1 0 100-2H9z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">INVOICE</h3>
                    <p className="text-green-100 text-sm">Billing & Payment Document</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-green-100">Invoice #</div>
                  <div className="font-mono text-lg">{record.invoice_number || 'INV-001'}</div>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 border-l-4 border-green-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Client</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.client_name || 'N/A'}</div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Invoice Details</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Invoice Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.invoice_date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Due Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.due_date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Status</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${record.status === 'Paid' ? 'bg-green-100 text-green-800' : record.status === 'Pending' ? 'bg-yellow-100 text-yellow-800' : 'bg-red-100 text-red-800'}`}>
                        {record.status || 'Unknown'}
                      </span>
                    </div>
                  </div>
                  <div className="col-span-3">
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Amount</label>
                    <div className="text-3xl font-bold text-green-600 mt-1">${(record.amount || 0).toFixed(2)}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case 'pay_statement':
        return (
          <div className="bg-white">
            <div className="bg-gradient-to-r from-indigo-600 to-indigo-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">PAY STATEMENT</h3>
                    <p className="text-indigo-100 text-sm">Employee Payroll Statement</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-indigo-100">Check #</div>
                  <div className="font-mono text-lg">{record.check_number || 'CHK001'}</div>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 border-l-4 border-indigo-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-indigo-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Pay Rate</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">${(record.pay_rate || 0).toFixed(2)} / hr</div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Pay Period Information</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Pay Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.pay_date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Period Start</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.period_start || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Period End</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.period_end || 'N/A'}</div>
                  </div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" />
                  <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Earnings & Deductions</h4>
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                  <h5 className="font-semibold text-green-700 mb-3">Earnings</h5>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span>Regular Pay</span>
                      <span className="font-medium">${(record.regular_pay || 0).toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Overtime Pay</span>
                      <span className="font-medium">${(record.overtime_pay || 0).toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Bonus</span>
                      <span className="font-medium">${(record.bonus || 0).toFixed(2)}</span>
                    </div>
                    <div className="border-t pt-2 mt-2 flex justify-between font-bold text-green-800">
                      <span>Gross Pay</span>
                      <span>${(record.gross_pay || 0).toFixed(2)}</span>
                    </div>
                  </div>
                </div>
                <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                  <h5 className="font-semibold text-red-700 mb-3">Deductions</h5>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span>Federal Tax</span>
                      <span className="font-medium">-${(record.federal_tax || 0).toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>State Tax</span>
                      <span className="font-medium">-${(record.state_tax || 0).toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Social Security</span>
                      <span className="font-medium">-${(record.social_security || 0).toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Medicare</span>
                      <span className="font-medium">-${(record.medicare || 0).toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Health Insurance</span>
                      <span className="font-medium">-${(record.health_insurance || 0).toFixed(2)}</span>
                    </div>
                    <div className="border-t pt-2 mt-2 flex justify-between font-bold text-red-800">
                      <span>Total Deductions</span>
                      <span>-${(record.total_deductions || 0).toFixed(2)}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6 bg-gradient-to-r from-indigo-500 to-indigo-700 text-white rounded-lg shadow-lg p-6">
              <div className="flex justify-between items-center">
                <span className="text-xl font-bold">NET PAY</span>
                <span className="text-3xl font-bold">${(record.net_pay || 0).toFixed(2)}</span>
              </div>
            </div>
          </div>
        );

      case 'job':
        return (
          <div className="bg-white">
            <div className="bg-gradient-to-r from-teal-600 to-teal-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
                      <path fillRule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.022 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">JOB CATALOG</h3>
                    <p className="text-teal-100 text-sm">Position Information</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-teal-100">Job ID</div>
                  <div className="font-mono text-lg">{record.job_id || 'JOB-001'}</div>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 border-l-4 border-teal-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-teal-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.586A2 2 0 0117.414 15H16v-2a1 1 0 10-2 0v2H6v-2a1 1 0 10-2 0v2H2.586A2 2 0 012 11.586V8a2 2 0 012-2h2zm4 0V5a1 1 0 011-1h2a1 1 0 011 1v1h-4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Position Details</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Job Title</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.job_title || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Department</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.department || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Reports To</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.reports_to || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">FLSA Status</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.flsa_status || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employment Type</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.employment_type || 'N/A'}</div>
                  </div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M8.433 7.418c.155-.103.346-.196.567-.267v1.698a2.5 2.5 0 00-1.134 0V7.151c.196.07.387.163.567.267zM11.567 7.151v1.698a2.5 2.5 0 00-1.134 0V7.151c.196.07.387.163.567.267z" />
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-13a1 1 0 10-2 0v.092a4.5 4.5 0 00-1.876.662A1 1 0 006.38 7.031a1 1 0 001.238.954 2.5 2.5 0 012.382 0 1 1 0 001.238-.954 1 1 0 00-.732-1.224A4.5 4.5 0 0011 5.092V5zM10 12a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Compensation Information</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Salary</label>
                    <div className="text-2xl font-bold text-green-600 mt-1">${(record.salary || 0).toFixed(2)}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Pay Frequency</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.pay_frequency || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Bonus Potential</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.bonus_potential || 'N/A'}</div>
                  </div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-gray-600" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
                  <path fillRule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Job Description</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="prose max-w-none text-gray-800">
                  {record.job_description || 'No job description available.'}
                </div>
              </div>
            </div>
          </div>
        );

      case 'expense':
        return (
          <div className="bg-white">
            <div className="bg-gradient-to-r from-orange-600 to-orange-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" />
                      <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">EXPENSE REPORT</h3>
                    <p className="text-orange-100 text-sm">Employee Expense Reimbursement</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-orange-100">Expense ID</div>
                  <div className="font-mono text-lg">{record.expense_id || 'EXP-001'}</div>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 border-l-4 border-orange-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-orange-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Expense Details</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Submission Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.submission_date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Category</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.category || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Status</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${record.status === 'Approved' ? 'bg-green-100 text-green-800' : record.status === 'Pending' ? 'bg-yellow-100 text-yellow-800' : 'bg-red-100 text-red-800'}`}>
                        {record.status || 'Unknown'}
                      </span>
                    </div>
                  </div>
                  <div className="col-span-3">
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Amount</label>
                    <div className="text-3xl font-bold text-orange-600 mt-1">${(record.amount || 0).toFixed(2)}</div>
                  </div>
                  <div className="col-span-3">
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Description</label>
                    <div className="text-gray-800 mt-1">{record.description || 'No description provided.'}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case 'tax_w2':
        const formType = record.form_type || 'W-2';
        let formTitle = 'W-2';
        let formDescription = 'Annual Wage and Tax Statement';

        switch (formType.toUpperCase()) {
          case '1099-NEC':
            formTitle = '1099-NEC';
            formDescription = 'Nonemployee Compensation';
            break;
          case '1099-MISC':
            formTitle = '1099-MISC';
            formDescription = 'Miscellaneous Income';
            break;
          case 'W-4':
            formTitle = 'W-4';
            formDescription = 'Employee Withholding Certificate';
            break;
          case '1099-INT':
            formTitle = '1099-INT';
            formDescription = 'Interest Income';
            break;
          case '1099-DIV':
            formTitle = '1099-DIV';
            formDescription = 'Dividend Income';
            break;
        }

        return (
          <div className="bg-white">
            <div className="bg-gradient-to-r from-purple-600 to-purple-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
                      <path fillRule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">TAX DOCUMENT ({formTitle})</h3>
                    <p className="text-purple-100 text-sm">{formDescription}</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-purple-100">Tax Year</div>
                  <div className="font-mono text-lg">{record.tax_year || new Date().getFullYear()}</div>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 border-l-4 border-purple-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employee Information</h4>
              </div>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employee ID</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.employee_id || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">SSN/TIN</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.ssn || '***-**-1234'}</div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" />
                  <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Tax Information</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                {formType === 'W-2' && (
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">1. Wages, tips, other compensation</label>
                      <div className="text-xl font-bold text-green-600 mt-1">${(record.wages || 0).toFixed(2)}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">2. Federal income tax withheld</label>
                      <div className="text-xl font-bold text-red-600 mt-1">${(record.federal_tax_withheld || 0).toFixed(2)}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">3. Social security wages</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${(record.ss_wages || 0).toFixed(2)}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">4. Social security tax withheld</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${(record.ss_tax_withheld || 0).toFixed(2)}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">5. Medicare wages and tips</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${(record.medicare_wages || 0).toFixed(2)}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">6. Medicare tax withheld</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${(record.medicare_tax_withheld || 0).toFixed(2)}</div>
                    </div>
                  </div>
                )}
                {formType === '1099-NEC' && (
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">1. Nonemployee compensation</label>
                      <div className="text-xl font-bold text-green-600 mt-1">${(record.nonemployee_compensation || 0).toFixed(2)}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">4. Federal income tax withheld</label>
                      <div className="text-xl font-bold text-red-600 mt-1">${(record.federal_tax_withheld || 0).toFixed(2)}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">5. State tax withheld</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">${(record.state_tax_withheld || 0).toFixed(2)}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">6. State/Payer's state no.</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.state_payer_no || 'N/A'}</div>
                    </div>
                  </div>
                )}
                {formType === 'W-4' && (
                  <div className="grid grid-cols-2 gap-6">
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Filing Status</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.filing_status || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Number of Dependents</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.dependents || 0}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Tax Jurisdiction</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.jurisdiction || 'N/A'}</div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">State Code</label>
                      <div className="text-lg font-semibold text-gray-900 mt-1">{record.state_code || 'N/A'}</div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        );

      default:
        return (
          <div className="bg-white p-6">
            <div className="bg-gradient-to-r from-gray-600 to-gray-800 text-white p-6 rounded-t-lg">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
                    <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">{recordType.toUpperCase()} PROFILE</h3>
                    <p className="text-gray-100 text-sm">Comprehensive Employee Information</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-sm text-gray-100">Employee ID</div>
                  <div className="font-mono text-lg">{record.employee_id || record.id}</div>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 border-l-4 border-gray-500 p-6 m-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-gray-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Personal Information</h4>
              </div>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Full Name</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.full_name || record.employee_name || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Date of Birth</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.dob || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Gender</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.gender || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Email</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.email || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Phone</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.phone || 'N/A'}</div>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Address</label>
                  <div className="text-lg font-semibold text-gray-900 mt-1">{record.address || 'N/A'}</div>
                </div>
              </div>
            </div>

            <div className="mx-6 mb-6">
              <div className="flex items-center space-x-2 mb-4">
                <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M6 6V5a3 3 0 013-3h2a3 3 0 013 3v1h2a2 2 0 012 2v3.586A2 2 0 0117.414 15H16v-2a1 1 0 10-2 0v2H6v-2a1 1 0 10-2 0v2H2.586A2 2 0 012 11.586V8a2 2 0 012-2h2zm4 0V5a1 1 0 011-1h2a1 1 0 011 1v1h-4z" clipRule="evenodd" />
                </svg>
                <h4 className="font-semibold text-gray-900 text-lg">Employment Details</h4>
              </div>
              <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Job Title</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.job_title || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Department</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.department || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Hire Date</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.hire_date || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Employment Status</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.employment_status || 'N/A'}</div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-gray-500 uppercase tracking-wide">Manager</label>
                    <div className="text-lg font-semibold text-gray-900 mt-1">{record.manager || 'N/A'}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex justify-center items-center p-4" onClick={onClose}>
      <div className="bg-gray-100 rounded-lg shadow-2xl w-full max-w-7xl max-h-full overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="sticky top-0 bg-gray-100 z-10 p-4 border-b border-gray-200 flex justify-between items-center">
          <div>
            <h2 className="text-lg font-semibold text-gray-800">{record.sub_client_company || record.client_name || record.customer_name || 'Customer Company Name'}</h2>
            <p className="text-sm text-gray-500">Generated on: {new Date().toLocaleDateString()}</p>
          </div>
          <div className="flex items-center space-x-2">
            <button onClick={handleDownload} className="text-gray-600 hover:text-gray-900 p-2 rounded-full bg-gray-200 hover:bg-gray-300 transition-colors">
              <Download size={20} />
            </button>
            <button onClick={handlePrint} className="text-gray-600 hover:text-gray-900 p-2 rounded-full bg-gray-200 hover:bg-gray-300 transition-colors">
              <Printer size={20} />
            </button>
            <button onClick={onClose} className="text-gray-600 hover:text-gray-900 p-2 rounded-full bg-gray-200 hover:bg-gray-300 transition-colors">
              <X size={20} />
            </button>
          </div>
        </div>

        <div id="facsimile-content" className="p-6">
          {renderRecordDetails()}
        </div>

        <div className="sticky bottom-0 bg-gray-100 z-10 p-4 border-t border-gray-200">
          <p className="text-xs text-gray-500 text-center">This is an official facsimile generated by {record.primary_client_name || record.tenant_name || 'Primary Client Name'}. For questions or concerns, please contact your account representative.</p>
        </div>
      </div>
    </div>
  );
}

